do $$
declare
  ver_id uuid;
begin
  select id into ver_id from public.test_versions where step_id = 'oacp' and is_active and published_at <= now() order by published_at desc limit 1;
  if ver_id is null then raise exception 'No active test_versions row found for step oacp'; end if;
  delete from public.test_questions where version_id = ver_id;
  insert into public.test_questions (version_id, order_index, prompt, choices, correct_index) values
  (ver_id, 1, 'Choose the sentence that is grammatically correct.', '["The officer and the witness were both present at the scene.","The officer and the witness was both present at the scene.","The officer along with the witness were both present at the scene.","The officer with the witness were both present at the scene."]'::jsonb, 0),
  (ver_id, 2, 'Which word best completes the sentence: The suspect gave a ____ statement to the investigator.', '["false","falsify","falsely","falseness"]'::jsonb, 0),
  (ver_id, 3, 'Which of the following sentences is the most concise?', '["The report was submitted on time.","The report, which was completed by the officer, was submitted in a timely manner.","The officer submitted the report, and it was on time.","On time, the report was submitted by the officer."]'::jsonb, 0),
  (ver_id, 4, 'Which of the following is spelled correctly?', '["Occurrence","Occurance","Occurence","Ocurrence"]'::jsonb, 0),
  (ver_id, 5, 'Which sentence has the correct punctuation?', '["The suspect said, ''I was not there at the time.''","I was not there at the time.","The suspect said, I was not there at the time.","The suspect said I was not there at the time."]'::jsonb, 0),
  (ver_id, 6, 'Language skill practice question 6: choose the best option.', '["Correct Language Answer 6","Wrong A6","Wrong B6","Wrong C6"]'::jsonb, 0),
  (ver_id, 7, 'Language skill practice question 7: choose the best option.', '["Correct Language Answer 7","Wrong A7","Wrong B7","Wrong C7"]'::jsonb, 0),
  (ver_id, 8, 'Language skill practice question 8: choose the best option.', '["Correct Language Answer 8","Wrong A8","Wrong B8","Wrong C8"]'::jsonb, 0),
  (ver_id, 9, 'Language skill practice question 9: choose the best option.', '["Correct Language Answer 9","Wrong A9","Wrong B9","Wrong C9"]'::jsonb, 0),
  (ver_id, 10, 'Language skill practice question 10: choose the best option.', '["Correct Language Answer 10","Wrong A10","Wrong B10","Wrong C10"]'::jsonb, 0),
  (ver_id, 11, 'Language skill practice question 11: choose the best option.', '["Correct Language Answer 11","Wrong A11","Wrong B11","Wrong C11"]'::jsonb, 0),
  (ver_id, 12, 'Language skill practice question 12: choose the best option.', '["Correct Language Answer 12","Wrong A12","Wrong B12","Wrong C12"]'::jsonb, 0),
  (ver_id, 13, 'Language skill practice question 13: choose the best option.', '["Correct Language Answer 13","Wrong A13","Wrong B13","Wrong C13"]'::jsonb, 0),
  (ver_id, 14, 'Language skill practice question 14: choose the best option.', '["Correct Language Answer 14","Wrong A14","Wrong B14","Wrong C14"]'::jsonb, 0),
  (ver_id, 15, 'Language skill practice question 15: choose the best option.', '["Correct Language Answer 15","Wrong A15","Wrong B15","Wrong C15"]'::jsonb, 0),
  (ver_id, 16, 'Language skill practice question 16: choose the best option.', '["Correct Language Answer 16","Wrong A16","Wrong B16","Wrong C16"]'::jsonb, 0),
  (ver_id, 17, 'Language skill practice question 17: choose the best option.', '["Correct Language Answer 17","Wrong A17","Wrong B17","Wrong C17"]'::jsonb, 0),
  (ver_id, 18, 'Language skill practice question 18: choose the best option.', '["Correct Language Answer 18","Wrong A18","Wrong B18","Wrong C18"]'::jsonb, 0),
  (ver_id, 19, 'Language skill practice question 19: choose the best option.', '["Correct Language Answer 19","Wrong A19","Wrong B19","Wrong C19"]'::jsonb, 0),
  (ver_id, 20, 'Language skill practice question 20: choose the best option.', '["Correct Language Answer 20","Wrong A20","Wrong B20","Wrong C20"]'::jsonb, 0),
  (ver_id, 21, 'If all patrol cars are vehicles, and some vehicles are marked, which statement must be true?', '["Some patrol cars may be marked vehicles.","All patrol cars are marked.","No patrol cars are marked.","All vehicles are patrol cars."]'::jsonb, 0),
  (ver_id, 22, 'Complete the analogy: Book is to Reading as Fork is to _____.', '["Eating","Drawing","Cooking","Sleeping"]'::jsonb, 0),
  (ver_id, 23, 'A suspect left at 2:00 pm and was seen 30 km away at 2:30 pm. What was the average speed?', '["60 km/h","30 km/h","90 km/h","120 km/h"]'::jsonb, 0),
  (ver_id, 24, 'Which number completes the series? 2, 4, 8, 16, __', '["32","20","24","30"]'::jsonb, 0),
  (ver_id, 25, 'If all officers are trained, and John is an officer, what can we conclude?', '["John is trained.","John is untrained.","John is not an officer.","Nothing can be concluded."]'::jsonb, 0),
  (ver_id, 26, 'Reasoning practice question 6: choose the best answer.', '["Correct Reasoning Answer 6","Wrong A6","Wrong B6","Wrong C6"]'::jsonb, 0),
  (ver_id, 27, 'Reasoning practice question 7: choose the best answer.', '["Correct Reasoning Answer 7","Wrong A7","Wrong B7","Wrong C7"]'::jsonb, 0),
  (ver_id, 28, 'Reasoning practice question 8: choose the best answer.', '["Correct Reasoning Answer 8","Wrong A8","Wrong B8","Wrong C8"]'::jsonb, 0),
  (ver_id, 29, 'Reasoning practice question 9: choose the best answer.', '["Correct Reasoning Answer 9","Wrong A9","Wrong B9","Wrong C9"]'::jsonb, 0),
  (ver_id, 30, 'Reasoning practice question 10: choose the best answer.', '["Correct Reasoning Answer 10","Wrong A10","Wrong B10","Wrong C10"]'::jsonb, 0),
  (ver_id, 31, 'Reasoning practice question 11: choose the best answer.', '["Correct Reasoning Answer 11","Wrong A11","Wrong B11","Wrong C11"]'::jsonb, 0),
  (ver_id, 32, 'Reasoning practice question 12: choose the best answer.', '["Correct Reasoning Answer 12","Wrong A12","Wrong B12","Wrong C12"]'::jsonb, 0),
  (ver_id, 33, 'Reasoning practice question 13: choose the best answer.', '["Correct Reasoning Answer 13","Wrong A13","Wrong B13","Wrong C13"]'::jsonb, 0),
  (ver_id, 34, 'Reasoning practice question 14: choose the best answer.', '["Correct Reasoning Answer 14","Wrong A14","Wrong B14","Wrong C14"]'::jsonb, 0),
  (ver_id, 35, 'Reasoning practice question 15: choose the best answer.', '["Correct Reasoning Answer 15","Wrong A15","Wrong B15","Wrong C15"]'::jsonb, 0),
  (ver_id, 36, 'Reasoning practice question 16: choose the best answer.', '["Correct Reasoning Answer 16","Wrong A16","Wrong B16","Wrong C16"]'::jsonb, 0),
  (ver_id, 37, 'Reasoning practice question 17: choose the best answer.', '["Correct Reasoning Answer 17","Wrong A17","Wrong B17","Wrong C17"]'::jsonb, 0),
  (ver_id, 38, 'Reasoning practice question 18: choose the best answer.', '["Correct Reasoning Answer 18","Wrong A18","Wrong B18","Wrong C18"]'::jsonb, 0),
  (ver_id, 39, 'Reasoning practice question 19: choose the best answer.', '["Correct Reasoning Answer 19","Wrong A19","Wrong B19","Wrong C19"]'::jsonb, 0),
  (ver_id, 40, 'Reasoning practice question 20: choose the best answer.', '["Correct Reasoning Answer 20","Wrong A20","Wrong B20","Wrong C20"]'::jsonb, 0),
  (ver_id, 41, 'An item costs $80 before tax. If tax is 13%, what is the total cost?', '["$90.40","$89.00","$91.50","$92.40"]'::jsonb, 0),
  (ver_id, 42, 'If a car travels 150 km in 3 hours, what is the average speed?', '["50 km/h","45 km/h","60 km/h","55 km/h"]'::jsonb, 0),
  (ver_id, 43, 'What is 25% of 200?', '["50","40","45","60"]'::jsonb, 0),
  (ver_id, 44, 'Solve: 3x = 21. What is x?', '["7","6","8","9"]'::jsonb, 0),
  (ver_id, 45, 'A police cruiser uses 12L of fuel for 100 km. How much fuel for 250 km?', '["30L","25L","28L","32L"]'::jsonb, 0),
  (ver_id, 46, 'Math practice question 6: solve the problem.', '["Correct Math Answer 6","Wrong A6","Wrong B6","Wrong C6"]'::jsonb, 0),
  (ver_id, 47, 'Math practice question 7: solve the problem.', '["Correct Math Answer 7","Wrong A7","Wrong B7","Wrong C7"]'::jsonb, 0),
  (ver_id, 48, 'Math practice question 8: solve the problem.', '["Correct Math Answer 8","Wrong A8","Wrong B8","Wrong C8"]'::jsonb, 0),
  (ver_id, 49, 'Math practice question 9: solve the problem.', '["Correct Math Answer 9","Wrong A9","Wrong B9","Wrong C9"]'::jsonb, 0),
  (ver_id, 50, 'Math practice question 10: solve the problem.', '["Correct Math Answer 10","Wrong A10","Wrong B10","Wrong C10"]'::jsonb, 0);
end $$;
